include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
