"""removing exam type enum

Revision ID: 032e87d16628
Revises: 44407dc9a4b3
Create Date: 2026-05-28 18:38:14.669495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '032e87d16628'
down_revision: Union[str, Sequence[str], None] = '44407dc9a4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_templates', 'exam_type',
               existing_type=postgresql.ENUM('quiz', 'midterm', 'final', 'practice', name='exam_type_enum'),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_exam_templates_exam_type'), 'exam_templates', ['exam_type'], unique=False)
    op.alter_column('exams', 'exam_type',
               existing_type=postgresql.ENUM('quiz', 'midterm', 'final', 'practice', name='exam_type_enum'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'exam_type',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('quiz', 'midterm', 'final', 'practice', name='exam_type_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_exam_templates_exam_type'), table_name='exam_templates')
    op.alter_column('exam_templates', 'exam_type',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('quiz', 'midterm', 'final', 'practice', name='exam_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
