"""remove token_version column

Revision ID: 04061708eb29
Revises: 6ebecccb1831
Create Date: 2026-02-12 05:50:48.225994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04061708eb29'
down_revision: Union[str, Sequence[str], None] = '6ebecccb1831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
