"""remove the delete rectriction on user delet vr2

Revision ID: 0ec21c5d52c5
Revises: d4260808a671
Create Date: 2026-03-14 18:36:53.596379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec21c5d52c5'
down_revision: Union[str, Sequence[str], None] = 'd4260808a671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
