"""add ai_request_logs table

Revision ID: 12914d169817
Revises: d8ae4b411698
Create Date: 2026-04-08 00:48:00.534284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12914d169817'
down_revision: Union[str, Sequence[str], None] = 'd8ae4b411698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('target_endpoint', sa.Text(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_entity_type', sa.String(length=100), nullable=True),
    sa.Column('primary_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('callback_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_request_logs_operation_status', 'ai_request_logs', ['operation_type', 'status'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_operation_type'), 'ai_request_logs', ['operation_type'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_request_id'), 'ai_request_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_ai_request_logs_status'), 'ai_request_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_request_logs_status'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_request_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_operation_type'), table_name='ai_request_logs')
    op.drop_index('ix_ai_request_logs_operation_status', table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    # ### end Alembic commands ###
