"""removing ai_ref_key from learning outcomes

Revision ID: 1d18f7626e0f
Revises: 2a1a6ac97350
Create Date: 2026-04-17 22:18:59.135656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d18f7626e0f'
down_revision: Union[str, Sequence[str], None] = '2a1a6ac97350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_outcomes_course_ai_ref'), table_name='learning_outcomes')
    op.drop_column('learning_outcomes', 'ai_ref_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_outcomes', sa.Column('ai_ref_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_learning_outcomes_course_ai_ref'), 'learning_outcomes', ['course_id', 'ai_ref_key'], unique=False)
    # ### end Alembic commands ###
