"""set server default for organizations.subscription_plan_id

Revision ID: 1df1b3dc07e2
Revises: 87203a7f116d
Create Date: 2026-02-05 00:28:28.749321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df1b3dc07e2'
down_revision: Union[str, Sequence[str], None] = '87203a7f116d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
