"""adding course_invitations table

Revision ID: 212a90a42978
Revises: 04061708eb29
Create Date: 2026-02-13 01:32:08.354628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212a90a42978'
down_revision: Union[str, Sequence[str], None] = '04061708eb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'access_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('access_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
