"""set server default for organizations.subscription_plan_id

Revision ID: 24f4c0aec0a1
Revises: 1df1b3dc07e2
Create Date: 2026-02-05 00:44:23.152346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f4c0aec0a1'
down_revision: Union[str, Sequence[str], None] = '1df1b3dc07e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
