"""change is_public to is_open_for_enrollment

Revision ID: 25b91dd6d309
Revises: de78e2345311
Create Date: 2026-03-11 14:00:46.130771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b91dd6d309'
down_revision: Union[str, Sequence[str], None] = 'de78e2345311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_open_for_enrollment', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_courses_is_public'), table_name='courses')
    op.create_index(op.f('ix_courses_is_open_for_enrollment'), 'courses', ['is_open_for_enrollment'], unique=False)
    op.drop_column('courses', 'is_public')
    op.add_column('topics', sa.Column('material_id', sa.Integer(), nullable=False))
    op.add_column('topics', sa.Column('is_ai_generated', sa.Boolean(), nullable=False))
    op.add_column('topics', sa.Column('is_reviewed', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_topics_module_id'), table_name='topics')
    op.drop_index(op.f('uq_topics_module_order'), table_name='topics')
    op.create_index(op.f('ix_topics_is_ai_generated'), 'topics', ['is_ai_generated'], unique=False)
    op.create_index(op.f('ix_topics_is_reviewed'), 'topics', ['is_reviewed'], unique=False)
    op.create_index(op.f('ix_topics_material_id'), 'topics', ['material_id'], unique=False)
    op.create_index('ix_topics_material_order', 'topics', ['material_id', 'order_index'], unique=False)
    op.create_index('ix_topics_material_parent', 'topics', ['material_id', 'parent_topic_id'], unique=False)
    op.drop_constraint(op.f('topics_module_id_fkey'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.drop_column('topics', 'is_required')
    op.drop_column('topics', 'estimated_duration_minutes')
    op.drop_column('topics', 'module_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(op.f('topics_module_id_fkey'), 'topics', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_topics_material_parent', table_name='topics')
    op.drop_index('ix_topics_material_order', table_name='topics')
    op.drop_index(op.f('ix_topics_material_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_is_reviewed'), table_name='topics')
    op.drop_index(op.f('ix_topics_is_ai_generated'), table_name='topics')
    op.create_index(op.f('uq_topics_module_order'), 'topics', ['module_id', 'order_index'], unique=True)
    op.create_index(op.f('ix_topics_module_id'), 'topics', ['module_id'], unique=False)
    op.drop_column('topics', 'is_reviewed')
    op.drop_column('topics', 'is_ai_generated')
    op.drop_column('topics', 'material_id')
    op.add_column('courses', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_courses_is_open_for_enrollment'), table_name='courses')
    op.create_index(op.f('ix_courses_is_public'), 'courses', ['is_public'], unique=False)
    op.drop_column('courses', 'is_open_for_enrollment')
    # ### end Alembic commands ###
