"""adding page_start and page_end to topics

Revision ID: 26e1e62e2175
Revises: 375e1b75bdfb
Create Date: 2026-06-26 03:11:31.329074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e1e62e2175'
down_revision: Union[str, Sequence[str], None] = '375e1b75bdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('topics', sa.Column('page_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'page_end')
    op.drop_column('topics', 'page_start')
    # ### end Alembic commands ###
