"""add draft_upload to material_status_enum

Revision ID: 279e77ece33a
Revises: d31cd2906d5d
Create Date: 2026-02-26 23:06:53.966676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279e77ece33a'
down_revision: Union[str, Sequence[str], None] = 'd31cd2906d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE material_status_enum ADD VALUE 'draft_upload'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
