"""adding use_ai_processing colum to material table

Revision ID: 2a1a6ac97350
Revises: b1aa71d1c7de
Create Date: 2026-04-15 21:30:45.378869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1a6ac97350'
down_revision: Union[str, Sequence[str], None] = 'b1aa71d1c7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "materials",
        sa.Column(
            "use_ai_processing",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'use_ai_processing')
    # ### end Alembic commands ###
