"""adding exam sectiona

Revision ID: 38e70d2dbb53
Revises: 8f5a4627976b
Create Date: 2026-05-26 08:35:48.419580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38e70d2dbb53'
down_revision: Union[str, Sequence[str], None] = '8f5a4627976b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_questions', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('uq_exam_questions_exam_order'), table_name='exam_questions')
    op.create_index(op.f('ix_exam_questions_section_id'), 'exam_questions', ['section_id'], unique=False)
    op.create_index('uq_exam_questions_section_order', 'exam_questions', ['section_id', 'order_index'], unique=True)
    op.drop_constraint(op.f('exam_questions_section_id_fkey'), 'exam_questions', type_='foreignkey')
    op.create_foreign_key(None, 'exam_questions', 'exam_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.add_column('exam_sections', sa.Column('question_type', sa.Enum('multiple_choice', 'multi_select', 'true_false', 'short_answer', 'essay', 'fill_in_the_blank', 'matching', 'ordering', 'numeric', 'code', name='question_type_enum'), nullable=False))
    op.add_column('exam_sections', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('exam_sections', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('exam_sections', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_exam_sections_exam_scope'), table_name='exam_sections')
    op.drop_index(op.f('ix_exam_sections_material_id'), table_name='exam_sections')
    op.drop_index(op.f('ix_exam_sections_module_id'), table_name='exam_sections')
    op.drop_index(op.f('ix_exam_sections_topic_id'), table_name='exam_sections')
    op.drop_constraint(op.f('exam_sections_topic_id_fkey'), 'exam_sections', type_='foreignkey')
    op.drop_constraint(op.f('exam_sections_module_id_fkey'), 'exam_sections', type_='foreignkey')
    op.drop_constraint(op.f('exam_sections_material_id_fkey'), 'exam_sections', type_='foreignkey')
    op.drop_column('exam_sections', 'module_id')
    op.drop_column('exam_sections', 'material_id')
    op.drop_column('exam_sections', 'difficulty')
    op.drop_column('exam_sections', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sections', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exam_sections', sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', 'mixed', name='exam_section_difficulty_enum'), autoincrement=False, nullable=True))
    op.add_column('exam_sections', sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exam_sections', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('exam_sections_material_id_fkey'), 'exam_sections', 'materials', ['material_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('exam_sections_module_id_fkey'), 'exam_sections', 'modules', ['module_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('exam_sections_topic_id_fkey'), 'exam_sections', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_exam_sections_topic_id'), 'exam_sections', ['topic_id'], unique=False)
    op.create_index(op.f('ix_exam_sections_module_id'), 'exam_sections', ['module_id'], unique=False)
    op.create_index(op.f('ix_exam_sections_material_id'), 'exam_sections', ['material_id'], unique=False)
    op.create_index(op.f('ix_exam_sections_exam_scope'), 'exam_sections', ['exam_id', 'topic_id', 'module_id', 'material_id'], unique=False)
    op.alter_column('exam_sections', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('exam_sections', 'updated_at')
    op.drop_column('exam_sections', 'created_at')
    op.drop_column('exam_sections', 'question_type')
    op.drop_constraint(None, 'exam_questions', type_='foreignkey')
    op.create_foreign_key(op.f('exam_questions_section_id_fkey'), 'exam_questions', 'exam_sections', ['section_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_exam_questions_section_order', table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_section_id'), table_name='exam_questions')
    op.create_index(op.f('uq_exam_questions_exam_order'), 'exam_questions', ['exam_id', 'order_index'], unique=True)
    op.alter_column('exam_questions', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
