"""adding exam templates2

Revision ID: 44407dc9a4b3
Revises: 4b97c4e4115b
Create Date: 2026-05-28 03:30:32.910198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '44407dc9a4b3'
down_revision: Union[str, Sequence[str], None] = '4b97c4e4115b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exam_type', postgresql.ENUM('quiz', 'midterm', 'final', 'practice', name='exam_type_enum', create_type=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_templates_course_id'), 'exam_templates', ['course_id'], unique=False)
    op.create_index('ix_exam_templates_course_type', 'exam_templates', ['course_id', 'exam_type'], unique=False)
    op.create_index('uq_exam_templates_course_name', 'exam_templates', ['course_id', 'name'], unique=True)
    op.create_table('exam_template_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('question_type', postgresql.ENUM('multiple_choice', 'multi_select', 'true_false', 'short_answer', 'essay', 'fill_in_the_blank', 'matching', 'ordering', 'numeric', 'code', name='question_type_enum', create_type=False), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('points_per_question', sa.Float(), nullable=False),
    sa.Column('section_score', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['exam_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_template_sections_template_id'), 'exam_template_sections', ['template_id'], unique=False)
    op.create_index('uq_exam_template_sections_template_order', 'exam_template_sections', ['template_id', 'order_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_exam_template_sections_template_order', table_name='exam_template_sections')
    op.drop_index(op.f('ix_exam_template_sections_template_id'), table_name='exam_template_sections')
    op.drop_table('exam_template_sections')
    op.drop_index('uq_exam_templates_course_name', table_name='exam_templates')
    op.drop_index('ix_exam_templates_course_type', table_name='exam_templates')
    op.drop_index(op.f('ix_exam_templates_course_id'), table_name='exam_templates')
    op.drop_table('exam_templates')
    # ### end Alembic commands ###
