"""make the `cours_invitation` token nullable

Revision ID: 4460146a8193
Revises: 7a05deb3e415
Create Date: 2026-02-13 23:03:43.769724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4460146a8193'
down_revision: Union[str, Sequence[str], None] = '7a05deb3e415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_invitations', 'token_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('course_invitations', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_invitations', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('course_invitations', 'token_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
