"""add_courses_search_vector

Revision ID: 5137fa8bb2cb
Revises: 0884df313ae3
Create Date: 2026-06-06 09:09:59.443106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5137fa8bb2cb'
down_revision: Union[str, Sequence[str], None] = '0884df313ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_courses_search_vector', 'courses', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

    # =========================
    # Backfill existing rows
    # =========================
    op.execute("""
        UPDATE courses
        SET search_vector =
            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(category, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(description, '')), 'C') ||
            setweight(to_tsvector('english', coalesce(
                (SELECT string_agg(value, ' ') FROM json_array_elements_text(tags)), ''
            )), 'C')
    """)

    # =========================
    # Create trigger function
    # =========================
    op.execute("""
        CREATE OR REPLACE FUNCTION courses_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.category, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(NEW.description, '')), 'C') ||
                setweight(to_tsvector('english', coalesce(
                    (SELECT string_agg(value, ' ') FROM json_array_elements_text(NEW.tags)), ''
                )), 'C');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # =========================
    # Create trigger
    # =========================
    op.execute("""
        CREATE TRIGGER courses_search_vector_trigger
        BEFORE INSERT OR UPDATE ON courses
        FOR EACH ROW EXECUTE FUNCTION courses_search_vector_update()
    """)


def downgrade() -> None:
    # =========================
    # Drop trigger + function
    # =========================
    op.execute("DROP TRIGGER IF EXISTS courses_search_vector_trigger ON courses")
    op.execute("DROP FUNCTION IF EXISTS courses_search_vector_update")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_search_vector', table_name='courses', postgresql_using='gin')
    op.drop_column('courses', 'search_vector')
    # ### end Alembic commands ###
