"""updating background_jobs

Revision ID: 5ee235419b3a
Revises: acd49c9e4b00
Create Date: 2026-07-11 15:45:43.928156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee235419b3a'
down_revision: Union[str, Sequence[str], None] = 'acd49c9e4b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_background_jobs_active_per_user', 'background_jobs', ['job_type', 'requested_by'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_background_jobs_active_per_user', table_name='background_jobs', postgresql_where=sa.text("status IN ('pending', 'processing')"))
    # ### end Alembic commands ###
