"""ubdating ai caht tabels

Revision ID: 647de231c7a4
Revises: 5137fa8bb2cb
Create Date: 2026-06-13 12:50:50.062166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647de231c7a4'
down_revision: Union[str, Sequence[str], None] = '5137fa8bb2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_chat_messages', 'model_used')
    op.drop_column('ai_chat_messages', 'credits_used')
    op.drop_column('ai_chat_sessions', 'temperature')
    op.drop_column('ai_chat_sessions', 'model_used')
    op.drop_column('ai_chat_sessions', 'credits_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_sessions', sa.Column('credits_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ai_chat_sessions', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ai_chat_messages', sa.Column('credits_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ai_chat_messages', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
