"""adding CourseInvitation table

Revision ID: 69296e247a52
Revises: 212a90a42978
Create Date: 2026-02-13 02:47:17.553399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69296e247a52'
down_revision: Union[str, Sequence[str], None] = '212a90a42978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=320), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='course_invite_status_enum'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'invited_email', name='uq_course_invite_course_email'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_course_invites_course_id', 'course_invitations', ['course_id'], unique=False)
    op.create_index('ix_course_invites_invited_email', 'course_invitations', ['invited_email'], unique=False)
    op.create_index('ix_course_invites_status', 'course_invitations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_invites_status', table_name='course_invitations')
    op.drop_index('ix_course_invites_invited_email', table_name='course_invitations')
    op.drop_index('ix_course_invites_course_id', table_name='course_invitations')
    op.drop_table('course_invitations')
    # ### end Alembic commands ###
