"""ubdating ai caht tabels vr2

Revision ID: 71d874304f27
Revises: 647de231c7a4
Create Date: 2026-06-13 13:51:05.835089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d874304f27'
down_revision: Union[str, Sequence[str], None] = '647de231c7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_messages', sa.Column('user_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ai_chat_messages', 'ai_chat_messages', ['user_message_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ai_chat_messages', 'prompt_tokens')
    op.drop_column('ai_chat_messages', 'token_count')
    op.drop_column('ai_chat_messages', 'completion_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_messages', sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_chat_messages', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_chat_messages', sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_chat_messages', type_='foreignkey')
    op.drop_column('ai_chat_messages', 'user_message_id')
    # ### end Alembic commands ###
