"""change the delete setting

Revision ID: 7a05deb3e415
Revises: ebdf83029ce6
Create Date: 2026-02-13 17:06:54.666550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a05deb3e415'
down_revision: Union[str, Sequence[str], None] = 'ebdf83029ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('courses_created_by_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_created_by_fkey'), 'courses', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('courses', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
