"""make is_open_for_enrollment not null

Revision ID: 8012e2c56ddb
Revises: 25b91dd6d309
Create Date: 2026-03-11 14:02:02.005204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8012e2c56ddb'
down_revision: Union[str, Sequence[str], None] = '25b91dd6d309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'is_open_for_enrollment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'is_open_for_enrollment',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
