"""adding credit_wallet table

Revision ID: 82dc7db45cfd
Revises: 32e7a3c73d51
Create Date: 2026-02-01 23:09:44.089992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82dc7db45cfd'
down_revision: Union[str, Sequence[str], None] = '32e7a3c73d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_member_id', sa.Integer(), nullable=False),
    sa.Column('balance_credits', sa.Integer(), nullable=False),
    sa.Column('monthly_allowance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_member_id'], ['organization_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_member_id'),
    sa.UniqueConstraint('organization_member_id', name='uq_member_credit_wallet_member')
    )
    op.drop_table('credit_wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_credits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('credit_wallets_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_wallets_pkey'))
    )
    op.drop_table('credit_wallet')
    # ### end Alembic commands ###
