"""initial models

Revision ID: 84dfbb9feaf0
Revises: 
Create Date: 2026-02-10 20:35:54.131715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dfbb9feaf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.Enum('free', 'basic', 'pro', 'enterprise', name='subscription_tier_enum'), nullable=False),
    sa.Column('max_teachers', sa.Integer(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('max_courses', sa.Integer(), nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False),
    sa.Column('allow_ai_chat', sa.Boolean(), nullable=False),
    sa.Column('allow_ai_question_gen', sa.Boolean(), nullable=False),
    sa.Column('allow_video_analysis', sa.Boolean(), nullable=False),
    sa.Column('allow_advanced_analytics', sa.Boolean(), nullable=False),
    sa.Column('allow_custom_branding', sa.Boolean(), nullable=False),
    sa.Column('allow_bulk_invites', sa.Boolean(), nullable=False),
    sa.Column('allow_api_access', sa.Boolean(), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('price_per_month', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_is_active'), 'subscription_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscription_plans_sort_order'), 'subscription_plans', ['sort_order'], unique=False)
    op.create_index(op.f('ix_subscription_plans_tier'), 'subscription_plans', ['tier'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('student_id', sa.String(length=100), nullable=True),
    sa.Column('university_email', sa.String(length=255), nullable=True),
    sa.Column('language_preference', sa.String(length=20), nullable=False),
    sa.Column('system_role', sa.Enum('USER', 'ADMIN', 'SUPPORT', name='system_role_enum'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_status', sa.Enum('active', 'suspended', 'deleted', 'pending_activation', name='account_status_enum'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('system', 'course', 'assignment', 'grade', 'message', 'announcement', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_channels', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('banner_url', sa.String(length=512), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=False),
    sa.Column('subscription_status', sa.Enum('active', 'past_due', 'canceled', name='subscription_status_enum'), nullable=False),
    sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('allow_self_registration', sa.Boolean(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('course_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_invite_code'), 'organizations', ['invite_code'], unique=True)
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_organizations_subscription_status'), 'organizations', ['subscription_status'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('assignment_alerts', sa.Boolean(), nullable=False),
    sa.Column('course_updates', sa.Boolean(), nullable=False),
    sa.Column('announcement_notifications', sa.Boolean(), nullable=False),
    sa.Column('grading_notifications', sa.Boolean(), nullable=False),
    sa.Column('deadline_reminders', sa.Boolean(), nullable=False),
    sa.Column('theme_mode', sa.Enum('light', 'dark', 'system', name='theme_mode_enum'), nullable=False),
    sa.Column('profile_visibility', sa.Enum('public', 'private', 'connections', name='profile_visibility_enum'), nullable=False),
    sa.Column('show_online_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('verify_email', 'reset_password', 'magic_login', name='user_token_type_enum'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_user_tokens_expires_at'), 'user_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_tokens_type'), 'user_tokens', ['type'], unique=False)
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('banner_image_url', sa.String(length=512), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('access_code', sa.String(length=50), nullable=True),
    sa.Column('visibility_level', sa.Enum('private', 'public', 'unlisted', name='course_visibility_level_enum'), nullable=False),
    sa.Column('requires_enrollment_approval', sa.Boolean(), nullable=False),
    sa.Column('learning_outcomes', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('course_type', sa.Enum('individual', 'organization', name='course_type_enum'), nullable=False),
    sa.Column('enrollment_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='course_status_enum'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                course_type = 'organization' AND organization_id IS NOT NULL\n            )\n            OR\n            (\n                course_type = 'individual' AND organization_id IS NULL\n            )\n            ", name='ck_courses_owner_matches_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_type'), 'courses', ['course_type'], unique=False)
    op.create_index('ix_courses_created_by_course_type', 'courses', ['created_by', 'course_type'], unique=False)
    op.create_index(op.f('ix_courses_is_public'), 'courses', ['is_public'], unique=False)
    op.create_index('ix_courses_org_id_title', 'courses', ['organization_id', 'title'], unique=False)
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_table('credit_wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_type', sa.Enum('individual', 'organization', name='credit_wallet_type_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('balance_credits', sa.Integer(), nullable=False),
    sa.Column('monthly_allowance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('allowance_reset_day', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                wallet_type = 'individual'\n                AND user_id IS NOT NULL\n                AND organization_id IS NULL\n            )\n            OR\n            (\n                wallet_type = 'organization'\n                AND organization_id IS NOT NULL\n                AND user_id IS NULL\n            )\n            ", name='ck_credit_wallet_owner'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_wallets_organization_id'), 'credit_wallets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_credit_wallets_user_id'), 'credit_wallets', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_wallets_wallet_type'), 'credit_wallets', ['wallet_type'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'instructor', 'assistant', 'student', name='organization_invitation_role_enum'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='organization_invitation_status_enum'), nullable=False),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_invitations_org_email_status', 'organization_invitations', ['organization_id', 'email', 'status'], unique=False)
    op.create_index(op.f('ix_organization_invitations_expires_at'), 'organization_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_organization_invitations_token'), 'organization_invitations', ['token'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'instructor', 'assistant', 'student', name='organization_member_role_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'inactive', name='organization_member_status_enum'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_members_user_id_status', 'organization_members', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_organization_members_role'), 'organization_members', ['role'], unique=False)
    op.create_index('uq_org_members_org_id_user_id', 'organization_members', ['organization_id', 'user_id'], unique=True)
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('session_title', sa.String(length=255), nullable=True),
    sa.Column('context_type', sa.Enum('general', 'course', 'material', 'question', name='ai_chat_context_type_enum'), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_context_type'), 'ai_chat_sessions', ['context_type'], unique=False)
    op.create_index('ix_ai_chat_sessions_course_last_msg', 'ai_chat_sessions', ['course_id', 'last_message_at'], unique=False)
    op.create_index('ix_ai_chat_sessions_user_active', 'ai_chat_sessions', ['user_id', 'is_active'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('active_students', sa.Integer(), nullable=False),
    sa.Column('active_teachers', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('total_enrollments', sa.Integer(), nullable=False),
    sa.Column('total_exams_taken', sa.Integer(), nullable=False),
    sa.Column('total_questions_answered', sa.Integer(), nullable=False),
    sa.Column('total_practice_sessions', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('ai_chat_usage', sa.Integer(), nullable=False),
    sa.Column('ai_question_gen_usage', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('total_courses', sa.Integer(), nullable=False),
    sa.Column('total_materials', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_dashboard_course_date', 'analytics', ['course_id', 'date'], unique=False)
    op.create_index('ix_analytics_dashboard_org_date', 'analytics', ['organization_id', 'date'], unique=False)
    op.create_index('ix_analytics_dashboard_user_date', 'analytics', ['user_id', 'date'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'completed', 'dropped', name='course_enrollment_status_enum'), nullable=False),
    sa.Column('enrollment_type', sa.Enum('self', 'invited', 'batch', name='course_enrollment_type_enum'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enrollments_enrollment_type'), 'course_enrollments', ['enrollment_type'], unique=False)
    op.create_index('ix_course_enrollments_student_status', 'course_enrollments', ['student_id', 'status'], unique=False)
    op.create_index('uq_course_enrollments_student_course', 'course_enrollments', ['student_id', 'course_id'], unique=True)
    op.create_table('course_instructors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('instructor', 'assistant', 'co_instructor', name='course_instructor_role_enum'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_instructors_instructor_id'), 'course_instructors', ['instructor_id'], unique=False)
    op.create_index('uq_course_instructors_course_instructor', 'course_instructors', ['course_id', 'instructor_id'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit_wallet_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('earned', 'spent', 'purchased', 'refunded', 'bonus', name='credit_transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount <> 0', name='ck_credit_tx_amount_nonzero'),
    sa.CheckConstraint('balance_after >= 0', name='ck_credit_tx_balance_after_nonneg'),
    sa.CheckConstraint('balance_before >= 0', name='ck_credit_tx_balance_before_nonneg'),
    sa.ForeignKeyConstraint(['credit_wallet_id'], ['credit_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_credit_wallet_id'), 'credit_transactions', ['credit_wallet_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_reason'), 'credit_transactions', ['reason'], unique=False)
    op.create_index(op.f('ix_credit_transactions_type'), 'credit_transactions', ['type'], unique=False)
    op.create_index('ix_credit_tx_reference_type_id', 'credit_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('exam_type', sa.Enum('quiz', 'midterm', 'final', 'practice', name='exam_type_enum'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enable_proctoring', sa.Boolean(), nullable=False),
    sa.Column('prevent_copy_paste', sa.Boolean(), nullable=False),
    sa.Column('prevent_tab_switch', sa.Boolean(), nullable=False),
    sa.Column('require_webcam', sa.Boolean(), nullable=False),
    sa.Column('require_microphone', sa.Boolean(), nullable=False),
    sa.Column('access_code', sa.String(length=50), nullable=True),
    sa.Column('ip_restrictions', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_available_from'), 'exams', ['available_from'], unique=False)
    op.create_index(op.f('ix_exams_available_to'), 'exams', ['available_to'], unique=False)
    op.create_index('ix_exams_course_published', 'exams', ['course_id', 'is_published'], unique=False)
    op.create_index(op.f('ix_exams_exam_type'), 'exams', ['exam_type'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_index('uq_modules_course_order', 'modules', ['course_id', 'order_index'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('credit_wallet_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('amount_money', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='payment_status_enum'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payer_email', sa.String(length=255), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('billing_interval', sa.Enum('one_time', 'monthly', 'yearly', name='billing_interval_enum'), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('\n            (\n                user_id IS NOT NULL AND organization_id IS NULL\n            )\n            OR\n            (\n                user_id IS NULL AND organization_id IS NOT NULL\n            )\n            ', name='ck_payments_payer_one'),
    sa.CheckConstraint('amount_money >= 0', name='ck_payments_amount_nonneg'),
    sa.CheckConstraint('credits_purchased >= 0', name='ck_payments_credits_nonneg'),
    sa.ForeignKeyConstraint(['credit_wallet_id'], ['credit_wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_credit_wallet_id'), 'payments', ['credit_wallet_id'], unique=False)
    op.create_index('ix_payments_org_created_at', 'payments', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_user_created_at', 'payments', ['user_id', 'created_at'], unique=False)
    op.create_table('question_banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Enum('practice', 'exam', 'homework', 'quiz', name='question_bank_purpose_enum'), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('show_answers', sa.Boolean(), nullable=False),
    sa.Column('show_explanations', sa.Boolean(), nullable=False),
    sa.Column('allow_retry', sa.Boolean(), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('access_level', sa.Enum('public', 'private', 'organization', name='question_bank_access_level_enum'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_banks_access_level'), 'question_banks', ['access_level'], unique=False)
    op.create_index(op.f('ix_question_banks_course_id'), 'question_banks', ['course_id'], unique=False)
    op.create_index(op.f('ix_question_banks_purpose'), 'question_banks', ['purpose'], unique=False)
    op.create_table('quick_quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', 'mixed', name='quick_quiz_difficulty_enum'), nullable=False),
    sa.Column('include_weak_points', sa.Boolean(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('generated', 'started', 'completed', 'expired', name='quick_quiz_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_quizzes_status'), 'quick_quizzes', ['status'], unique=False)
    op.create_index('ix_quick_quizzes_student_course_created', 'quick_quizzes', ['student_id', 'course_id', 'created_at'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('user', 'assistant', 'system', name='ai_chat_message_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_message_type'), 'ai_chat_messages', ['message_type'], unique=False)
    op.create_index('ix_ai_chat_messages_session_created', 'ai_chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('practice', 'review', 'test', name='practice_session_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='practice_session_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practice_sessions_bank_started', 'practice_sessions', ['question_bank_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_practice_sessions_status'), 'practice_sessions', ['status'], unique=False)
    op.create_index('ix_practice_sessions_student_course_started', 'practice_sessions', ['student_id', 'course_id', 'started_at'], unique=False)
    op.create_table('student_exam_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'graded', 'expired', name='exam_attempt_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('percentage_score', sa.Float(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('unanswered_count', sa.Integer(), nullable=True),
    sa.Column('cheating_flags', sa.JSON(), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('proctoring_data', sa.JSON(), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('teacher_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_exam_attempts_exam_started', 'student_exam_attempts', ['exam_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_student_exam_attempts_status'), 'student_exam_attempts', ['status'], unique=False)
    op.create_index('uq_student_exam_attempts_student_exam_attempt', 'student_exam_attempts', ['student_id', 'exam_id', 'attempt_number'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('parent_topic_id', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_module_id'), 'topics', ['module_id'], unique=False)
    op.create_index(op.f('ix_topics_parent_topic_id'), 'topics', ['parent_topic_id'], unique=False)
    op.create_index('uq_topics_module_order', 'topics', ['module_id', 'order_index'], unique=True)
    op.create_table('exam_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', 'mixed', name='exam_section_difficulty_enum'), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('section_score', sa.Float(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('must_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sections_topic_id'), 'exam_sections', ['topic_id'], unique=False)
    op.create_index('uq_exam_sections_exam_order', 'exam_sections', ['exam_id', 'order_index'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('video', 'pdf', 'document', 'presentation', 'link', 'quiz', name='material_type_enum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'error', name='material_status_enum'), nullable=False),
    sa.Column('text_extracted', sa.Boolean(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=False),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    op.create_index(op.f('ix_materials_topic_id'), 'materials', ['topic_id'], unique=False)
    op.create_index('ix_materials_topic_type', 'materials', ['topic_id', 'type'], unique=False)
    op.create_index(op.f('ix_materials_type'), 'materials', ['type'], unique=False)
    op.create_table('quick_quiz_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quick_quiz_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quick_quiz_id'], ['quick_quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_quiz_topics_topic_id'), 'quick_quiz_topics', ['topic_id'], unique=False)
    op.create_index('uq_quick_quiz_topics_quiz_topic', 'quick_quiz_topics', ['quick_quiz_id', 'topic_id'], unique=True)
    op.create_table('weak_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('weakness_score', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_weak_points_course_topic', 'weak_points', ['course_id', 'topic_id'], unique=False)
    op.create_index(op.f('ix_weak_points_weakness_score'), 'weak_points', ['weakness_score'], unique=False)
    op.create_index('uq_student_weak_points_student_course_topic', 'weak_points', ['student_id', 'course_id', 'topic_id'], unique=True)
    op.create_table('ai_question_generation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='ai_question_generation_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_qgen_material_topic_created', 'ai_question_generation_logs', ['material_id', 'topic_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_question_generation_logs_status'), 'ai_question_generation_logs', ['status'], unique=False)
    op.create_table('learning_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('material', 'question', 'topic_review', 'practice_session', name='learning_recommendation_type_enum'), nullable=False),
    sa.Column('target_topic_id', sa.Integer(), nullable=True),
    sa.Column('target_material_id', sa.Integer(), nullable=True),
    sa.Column('target_question_bank_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_benefit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_question_bank_id'], ['question_banks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_recommendations_is_completed'), 'learning_recommendations', ['is_completed'], unique=False)
    op.create_index('ix_learning_recommendations_student_course_generated', 'learning_recommendations', ['student_id', 'course_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_learning_recommendations_target_material_id'), 'learning_recommendations', ['target_material_id'], unique=False)
    op.create_index(op.f('ix_learning_recommendations_target_topic_id'), 'learning_recommendations', ['target_topic_id'], unique=False)
    op.create_table('material_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('start_time_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_chunks_material_id'), 'material_chunks', ['material_id'], unique=False)
    op.create_index('uq_material_chunks_material_index', 'material_chunks', ['material_id', 'chunk_index'], unique=True)
    op.create_table('video_timestamps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time_seconds', sa.Integer(), nullable=False),
    sa.Column('end_time_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time_seconds > start_time_seconds', name='ck_video_ts_range_valid'),
    sa.CheckConstraint('end_time_seconds >= 0', name='ck_video_ts_end_nonneg'),
    sa.CheckConstraint('start_time_seconds >= 0', name='ck_video_ts_start_nonneg'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_timestamps_material_start', 'video_timestamps', ['material_id', 'start_time_seconds'], unique=False)
    op.create_index(op.f('ix_video_timestamps_topic_id'), 'video_timestamps', ['topic_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('video_timestamp_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', name='question_type_enum'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='question_difficulty_enum'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ai_generated', 'imported', name='question_source_enum'), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='question_approval_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('grading_rubric', sa.JSON(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('auto_gradable', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_time_seconds', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_timestamp_id'], ['video_timestamps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_approval_status'), 'questions', ['approval_status'], unique=False)
    op.create_index('ix_questions_bank_topic', 'questions', ['bank_id', 'topic_id'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_material_id'), 'questions', ['material_id'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_questions_usage_count'), 'questions', ['usage_count'], unique=False)
    op.create_table('ai_question_generation_log_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['ai_question_generation_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_question_generation_log_questions_question_id'), 'ai_question_generation_log_questions', ['question_id'], unique=False)
    op.create_index('uq_ai_qgen_log_question', 'ai_question_generation_log_questions', ['log_id', 'question_id'], unique=True)
    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('custom_points', sa.Float(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_questions_question_id'), 'exam_questions', ['question_id'], unique=False)
    op.create_index('uq_exam_questions_exam_order', 'exam_questions', ['exam_id', 'order_index'], unique=True)
    op.create_index('uq_exam_questions_exam_question', 'exam_questions', ['exam_id', 'question_id'], unique=True)
    op.create_table('learning_recommendation_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['learning_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_recommendation_questions_question_id'), 'learning_recommendation_questions', ['question_id'], unique=False)
    op.create_index('uq_learning_recommendation_questions_rec_question', 'learning_recommendation_questions', ['recommendation_id', 'question_id'], unique=True)
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_index('uq_question_options_question_order', 'question_options', ['question_id', 'order_index'], unique=True)
    op.create_table('question_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_reason', sa.String(length=255), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_recommendations_is_completed'), 'question_recommendations', ['is_completed'], unique=False)
    op.create_index(op.f('ix_question_recommendations_question_id'), 'question_recommendations', ['question_id'], unique=False)
    op.create_index('ix_question_recommendations_student_course_suggested', 'question_recommendations', ['student_id', 'course_id', 'suggested_at'], unique=False)
    op.create_table('question_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_tags_tag_name'), 'question_tags', ['tag_name'], unique=False)
    op.create_index('uq_question_tags_question_tag', 'question_tags', ['question_id', 'tag_name'], unique=True)
    op.create_table('student_question_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('times_attempted', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_wrong', sa.Integer(), nullable=False),
    sa.Column('average_time_seconds', sa.Float(), nullable=True),
    sa.Column('mastery_level', sa.Enum('unattempted', 'beginner', 'intermediate', 'advanced', 'mastered', name='question_mastery_level_enum'), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_correct_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_question_progress_mastery_level'), 'student_question_progress', ['mastery_level'], unique=False)
    op.create_index(op.f('ix_student_question_progress_question_id'), 'student_question_progress', ['question_id'], unique=False)
    op.create_index('uq_student_question_progress_student_question', 'student_question_progress', ['student_id', 'question_id'], unique=True)
    op.create_table('practice_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_answers_question_id'), 'practice_answers', ['question_id'], unique=False)
    op.create_index('uq_practice_answers_session_question', 'practice_answers', ['session_id', 'question_id'], unique=True)
    op.create_table('student_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('exam_question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Float(), nullable=True),
    sa.Column('auto_graded', sa.Boolean(), nullable=False),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('teacher_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['student_exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_answers_exam_question_id'), 'student_answers', ['exam_question_id'], unique=False)
    op.create_index('uq_student_answers_attempt_exam_question', 'student_answers', ['attempt_id', 'exam_question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_student_answers_attempt_exam_question', table_name='student_answers')
    op.drop_index(op.f('ix_student_answers_exam_question_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index('uq_practice_answers_session_question', table_name='practice_answers')
    op.drop_index(op.f('ix_practice_answers_question_id'), table_name='practice_answers')
    op.drop_table('practice_answers')
    op.drop_index('uq_student_question_progress_student_question', table_name='student_question_progress')
    op.drop_index(op.f('ix_student_question_progress_question_id'), table_name='student_question_progress')
    op.drop_index(op.f('ix_student_question_progress_mastery_level'), table_name='student_question_progress')
    op.drop_table('student_question_progress')
    op.drop_index('uq_question_tags_question_tag', table_name='question_tags')
    op.drop_index(op.f('ix_question_tags_tag_name'), table_name='question_tags')
    op.drop_table('question_tags')
    op.drop_index('ix_question_recommendations_student_course_suggested', table_name='question_recommendations')
    op.drop_index(op.f('ix_question_recommendations_question_id'), table_name='question_recommendations')
    op.drop_index(op.f('ix_question_recommendations_is_completed'), table_name='question_recommendations')
    op.drop_table('question_recommendations')
    op.drop_index('uq_question_options_question_order', table_name='question_options')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('uq_learning_recommendation_questions_rec_question', table_name='learning_recommendation_questions')
    op.drop_index(op.f('ix_learning_recommendation_questions_question_id'), table_name='learning_recommendation_questions')
    op.drop_table('learning_recommendation_questions')
    op.drop_index('uq_exam_questions_exam_question', table_name='exam_questions')
    op.drop_index('uq_exam_questions_exam_order', table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_question_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index('uq_ai_qgen_log_question', table_name='ai_question_generation_log_questions')
    op.drop_index(op.f('ix_ai_question_generation_log_questions_question_id'), table_name='ai_question_generation_log_questions')
    op.drop_table('ai_question_generation_log_questions')
    op.drop_index(op.f('ix_questions_usage_count'), table_name='questions')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_material_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index('ix_questions_bank_topic', table_name='questions')
    op.drop_index(op.f('ix_questions_approval_status'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_video_timestamps_topic_id'), table_name='video_timestamps')
    op.drop_index('ix_video_timestamps_material_start', table_name='video_timestamps')
    op.drop_table('video_timestamps')
    op.drop_index('uq_material_chunks_material_index', table_name='material_chunks')
    op.drop_index(op.f('ix_material_chunks_material_id'), table_name='material_chunks')
    op.drop_table('material_chunks')
    op.drop_index(op.f('ix_learning_recommendations_target_topic_id'), table_name='learning_recommendations')
    op.drop_index(op.f('ix_learning_recommendations_target_material_id'), table_name='learning_recommendations')
    op.drop_index('ix_learning_recommendations_student_course_generated', table_name='learning_recommendations')
    op.drop_index(op.f('ix_learning_recommendations_is_completed'), table_name='learning_recommendations')
    op.drop_table('learning_recommendations')
    op.drop_index(op.f('ix_ai_question_generation_logs_status'), table_name='ai_question_generation_logs')
    op.drop_index('ix_ai_qgen_material_topic_created', table_name='ai_question_generation_logs')
    op.drop_table('ai_question_generation_logs')
    op.drop_index('uq_student_weak_points_student_course_topic', table_name='weak_points')
    op.drop_index(op.f('ix_weak_points_weakness_score'), table_name='weak_points')
    op.drop_index('ix_student_weak_points_course_topic', table_name='weak_points')
    op.drop_table('weak_points')
    op.drop_index('uq_quick_quiz_topics_quiz_topic', table_name='quick_quiz_topics')
    op.drop_index(op.f('ix_quick_quiz_topics_topic_id'), table_name='quick_quiz_topics')
    op.drop_table('quick_quiz_topics')
    op.drop_index(op.f('ix_materials_type'), table_name='materials')
    op.drop_index('ix_materials_topic_type', table_name='materials')
    op.drop_index(op.f('ix_materials_topic_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_table('materials')
    op.drop_index('uq_exam_sections_exam_order', table_name='exam_sections')
    op.drop_index(op.f('ix_exam_sections_topic_id'), table_name='exam_sections')
    op.drop_table('exam_sections')
    op.drop_index('uq_topics_module_order', table_name='topics')
    op.drop_index(op.f('ix_topics_parent_topic_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_module_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index('uq_student_exam_attempts_student_exam_attempt', table_name='student_exam_attempts')
    op.drop_index(op.f('ix_student_exam_attempts_status'), table_name='student_exam_attempts')
    op.drop_index('ix_student_exam_attempts_exam_started', table_name='student_exam_attempts')
    op.drop_table('student_exam_attempts')
    op.drop_index('ix_practice_sessions_student_course_started', table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_status'), table_name='practice_sessions')
    op.drop_index('ix_practice_sessions_bank_started', table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index('ix_ai_chat_messages_session_created', table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_message_type'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index('ix_quick_quizzes_student_course_created', table_name='quick_quizzes')
    op.drop_index(op.f('ix_quick_quizzes_status'), table_name='quick_quizzes')
    op.drop_table('quick_quizzes')
    op.drop_index(op.f('ix_question_banks_purpose'), table_name='question_banks')
    op.drop_index(op.f('ix_question_banks_course_id'), table_name='question_banks')
    op.drop_index(op.f('ix_question_banks_access_level'), table_name='question_banks')
    op.drop_table('question_banks')
    op.drop_index('ix_payments_user_created_at', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_index('ix_payments_org_created_at', table_name='payments')
    op.drop_index(op.f('ix_payments_credit_wallet_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_modules_course_order', table_name='modules')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_exams_exam_type'), table_name='exams')
    op.drop_index('ix_exams_course_published', table_name='exams')
    op.drop_index(op.f('ix_exams_available_to'), table_name='exams')
    op.drop_index(op.f('ix_exams_available_from'), table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_credit_tx_reference_type_id', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_reason'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_credit_wallet_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('uq_course_instructors_course_instructor', table_name='course_instructors')
    op.drop_index(op.f('ix_course_instructors_instructor_id'), table_name='course_instructors')
    op.drop_table('course_instructors')
    op.drop_index('uq_course_enrollments_student_course', table_name='course_enrollments')
    op.drop_index('ix_course_enrollments_student_status', table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_enrollment_type'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index('ix_analytics_dashboard_user_date', table_name='analytics')
    op.drop_index('ix_analytics_dashboard_org_date', table_name='analytics')
    op.drop_index('ix_analytics_dashboard_course_date', table_name='analytics')
    op.drop_table('analytics')
    op.drop_index('ix_ai_chat_sessions_user_active', table_name='ai_chat_sessions')
    op.drop_index('ix_ai_chat_sessions_course_last_msg', table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_context_type'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_index('uq_org_members_org_id_user_id', table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_role'), table_name='organization_members')
    op.drop_index('ix_org_members_user_id_status', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invitations_token'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_expires_at'), table_name='organization_invitations')
    op.drop_index('ix_org_invitations_org_email_status', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_credit_wallets_wallet_type'), table_name='credit_wallets')
    op.drop_index(op.f('ix_credit_wallets_user_id'), table_name='credit_wallets')
    op.drop_index(op.f('ix_credit_wallets_organization_id'), table_name='credit_wallets')
    op.drop_table('credit_wallets')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_index('ix_courses_org_id_title', table_name='courses')
    op.drop_index(op.f('ix_courses_is_public'), table_name='courses')
    op.drop_index('ix_courses_created_by_course_type', table_name='courses')
    op.drop_index(op.f('ix_courses_course_type'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_type'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_expires_at'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_organizations_subscription_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_invite_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_tier'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_sort_order'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_is_active'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
