"""set server default for organizations.subscription_plan_id

Revision ID: 87203a7f116d
Revises: bdb1470522c9
Create Date: 2026-02-05 00:22:04.952547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87203a7f116d'
down_revision: Union[str, Sequence[str], None] = 'bdb1470522c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
