"""adding snapshots to exam questions

Revision ID: 8f5a4627976b
Revises: 1d18f7626e0f
Create Date: 2026-05-22 16:01:53.051462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f5a4627976b'
down_revision: Union[str, Sequence[str], None] = '1d18f7626e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_questions', sa.Column('snapshot_topic_id', sa.Integer(), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_question_text', sa.Text(), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_explanation', sa.Text(), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_type', sa.Text(), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_difficulty', sa.Text(), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_expected_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_grading_rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_max_score', sa.Float(), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_auto_gradable', sa.Boolean(), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_source_question_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_questions', sa.Column('snapshot_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_questions', 'snapshot_created_at')
    op.drop_column('exam_questions', 'snapshot_source_question_updated_at')
    op.drop_column('exam_questions', 'snapshot_tags')
    op.drop_column('exam_questions', 'snapshot_auto_gradable')
    op.drop_column('exam_questions', 'snapshot_max_score')
    op.drop_column('exam_questions', 'snapshot_grading_rubric')
    op.drop_column('exam_questions', 'snapshot_expected_answer')
    op.drop_column('exam_questions', 'snapshot_difficulty')
    op.drop_column('exam_questions', 'snapshot_type')
    op.drop_column('exam_questions', 'snapshot_options')
    op.drop_column('exam_questions', 'snapshot_explanation')
    op.drop_column('exam_questions', 'snapshot_question_text')
    op.drop_column('exam_questions', 'snapshot_topic_id')
    # ### end Alembic commands ###
