"""reblace the avatarURL with avatarKEY

Revision ID: a3d2fe4aec8f
Revises: 98d1b4715c5e
Create Date: 2026-02-24 02:14:07.071516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d2fe4aec8f'
down_revision: Union[str, Sequence[str], None] = '98d1b4715c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=False)
    op.add_column('users', sa.Column('avatar_key', sa.String(length=512), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_key')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_column('courses', 'course_code')
    # ### end Alembic commands ###
