"""adding question_pool

Revision ID: aceac70f0bde
Revises: c9b1984f4798
Create Date: 2026-06-27 17:49:21.743190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'aceac70f0bde'
down_revision: Union[str, Sequence[str], None] = 'c9b1984f4798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_pool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', postgresql.ENUM(name='question_type_enum', create_type=False), nullable=False),
    sa.Column('difficulty', postgresql.ENUM(name='question_difficulty_enum', create_type=False), nullable=False),
    sa.Column('source', postgresql.ENUM(name='question_source_enum', create_type=False), nullable=False),
    sa.Column('expected_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grading_rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('auto_gradable', sa.Boolean(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_questions_pool_max_score_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pool_topic_type_difficulty', 'questions_pool', ['topic_id', 'type', 'difficulty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pool_topic_type_difficulty', table_name='questions_pool')
    op.drop_table('questions_pool')
    # ### end Alembic commands ###
