"""update the ai request log table

Revision ID: b1aa71d1c7de
Revises: e7c95895fde1
Create Date: 2026-04-14 02:36:27.243238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1aa71d1c7de'
down_revision: Union[str, Sequence[str], None] = 'e7c95895fde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_request_logs', sa.Column('http_method', sa.String(length=10), nullable=False))
    op.add_column('ai_request_logs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_request_logs', sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ai_request_logs', 'request_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('ai_request_logs', 'response_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ai_request_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_ai_request_logs_course_operation', 'ai_request_logs', ['course_id', 'operation_type'], unique=False)
    op.create_index('ix_ai_request_logs_status_expires_at', 'ai_request_logs', ['status', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_request_logs_status_expires_at', table_name='ai_request_logs')
    op.drop_index('ix_ai_request_logs_course_operation', table_name='ai_request_logs')
    op.alter_column('ai_request_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ai_request_logs', 'response_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ai_request_logs', 'request_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('ai_request_logs', 'last_error_at')
    op.drop_column('ai_request_logs', 'completed_at')
    op.drop_column('ai_request_logs', 'http_method')
    # ### end Alembic commands ###
