"""make LO level nullable

Revision ID: c9b1984f4798
Revises: ca90b28499c4
Create Date: 2026-06-26 06:36:03.295082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9b1984f4798'
down_revision: Union[str, Sequence[str], None] = 'ca90b28499c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_outcomes', 'level',
               existing_type=postgresql.ENUM('foundational', 'intermediate', 'advanced', name='learning_outcome_level_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_outcomes', 'level',
               existing_type=postgresql.ENUM('foundational', 'intermediate', 'advanced', name='learning_outcome_level_enum'),
               nullable=False)
    # ### end Alembic commands ###
