"""adding parent_learning_outcome_id

Revision ID: ca90b28499c4
Revises: 26e1e62e2175
Create Date: 2026-06-26 06:34:42.293679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca90b28499c4'
down_revision: Union[str, Sequence[str], None] = '26e1e62e2175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_outcomes', sa.Column('parent_learning_outcome_id', sa.Integer(), nullable=True))
    op.create_index('ix_learning_outcomes_course_parent', 'learning_outcomes', ['course_id', 'parent_learning_outcome_id'], unique=False)
    op.create_index(op.f('ix_learning_outcomes_parent_learning_outcome_id'), 'learning_outcomes', ['parent_learning_outcome_id'], unique=False)
    op.create_foreign_key(None, 'learning_outcomes', 'learning_outcomes', ['parent_learning_outcome_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_outcomes', type_='foreignkey')
    op.drop_index(op.f('ix_learning_outcomes_parent_learning_outcome_id'), table_name='learning_outcomes')
    op.drop_index('ix_learning_outcomes_course_parent', table_name='learning_outcomes')
    op.drop_column('learning_outcomes', 'parent_learning_outcome_id')
    # ### end Alembic commands ###
