"""update the modules and the materials tables

Revision ID: d31cd2906d5d
Revises: a3d2fe4aec8f
Create Date: 2026-02-26 00:56:25.037238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31cd2906d5d'
down_revision: Union[str, Sequence[str], None] = 'a3d2fe4aec8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('cover_image_key', sa.String(length=512), nullable=True))
    op.add_column('courses', sa.Column('banner_image_key', sa.String(length=512), nullable=True))
    op.drop_column('courses', 'cover_image_url')
    op.drop_column('courses', 'banner_image_url')
    op.add_column('materials', sa.Column('module_id', sa.Integer(), nullable=False))
    op.add_column('materials', sa.Column('storage_key', sa.String(length=1024), nullable=False))
    op.add_column('materials', sa.Column('thumbnail_key', sa.String(length=1024), nullable=True))
    op.add_column('materials', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('materials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('materials', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_materials_topic_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_topic_type'), table_name='materials')
    op.create_index(op.f('ix_materials_module_id'), 'materials', ['module_id'], unique=False)
    op.create_index('ix_materials_module_status', 'materials', ['module_id', 'status'], unique=False)
    op.create_index('ix_materials_module_type', 'materials', ['module_id', 'type'], unique=False)
    op.create_index(op.f('ix_materials_uploaded_by'), 'materials', ['uploaded_by'], unique=False)
    op.drop_constraint(op.f('materials_topic_id_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('materials', 'thumbnail_url')
    op.drop_column('materials', 'file_url')
    op.drop_column('materials', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('file_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('thumbnail_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_topic_id_fkey'), 'materials', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_materials_uploaded_by'), table_name='materials')
    op.drop_index('ix_materials_module_type', table_name='materials')
    op.drop_index('ix_materials_module_status', table_name='materials')
    op.drop_index(op.f('ix_materials_module_id'), table_name='materials')
    op.create_index(op.f('ix_materials_topic_type'), 'materials', ['topic_id', 'type'], unique=False)
    op.create_index(op.f('ix_materials_topic_id'), 'materials', ['topic_id'], unique=False)
    op.alter_column('materials', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('materials', 'updated_at')
    op.drop_column('materials', 'created_at')
    op.drop_column('materials', 'thumbnail_key')
    op.drop_column('materials', 'storage_key')
    op.drop_column('materials', 'module_id')
    op.add_column('courses', sa.Column('banner_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('cover_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('courses', 'banner_image_key')
    op.drop_column('courses', 'cover_image_key')
    # ### end Alembic commands ###
