"""remove the delete rectriction on user delet

Revision ID: d4260808a671
Revises: 5e730cd0341f
Create Date: 2026-03-14 18:29:15.457866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4260808a671'
down_revision: Union[str, Sequence[str], None] = '5e730cd0341f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('materials_uploaded_by_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_uploaded_by_fkey'), 'materials', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
