"""modifay the questions table vr2

Revision ID: d8ae4b411698
Revises: 0ec21c5d52c5
Create Date: 2026-03-24 18:36:49.343123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ae4b411698'
down_revision: Union[str, Sequence[str], None] = '0ec21c5d52c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'grading_rubric',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('questions', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('questions', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_questions_course_material'), table_name='questions')
    op.drop_index(op.f('ix_questions_course_module'), table_name='questions')
    op.drop_index(op.f('ix_questions_material_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_module_id'), table_name='questions')
    op.create_index('ix_questions_course_approval_status', 'questions', ['course_id', 'approval_status'], unique=False)
    op.create_index('ix_questions_course_difficulty', 'questions', ['course_id', 'difficulty'], unique=False)
    op.create_index('ix_questions_course_type', 'questions', ['course_id', 'type'], unique=False)
    op.create_index('ix_questions_topic_type', 'questions', ['topic_id', 'type'], unique=False)
    op.drop_constraint(op.f('questions_reviewed_by_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('questions_created_by_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('questions_video_timestamp_id_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('questions_material_id_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('questions_module_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('questions', 'module_id')
    op.drop_column('questions', 'video_timestamp_id')
    op.drop_column('questions', 'reviewed_by')
    op.drop_column('questions', 'material_id')
    op.drop_column('questions', 'reviewed_at')
    op.drop_column('questions', 'review_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('video_timestamp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_module_id_fkey'), 'questions', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('questions_material_id_fkey'), 'questions', 'materials', ['material_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('questions_video_timestamp_id_fkey'), 'questions', 'video_timestamps', ['video_timestamp_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('questions_created_by_fkey'), 'questions', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('questions_reviewed_by_fkey'), 'questions', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_questions_topic_type', table_name='questions')
    op.drop_index('ix_questions_course_type', table_name='questions')
    op.drop_index('ix_questions_course_difficulty', table_name='questions')
    op.drop_index('ix_questions_course_approval_status', table_name='questions')
    op.create_index(op.f('ix_questions_module_id'), 'questions', ['module_id'], unique=False)
    op.create_index(op.f('ix_questions_material_id'), 'questions', ['material_id'], unique=False)
    op.create_index(op.f('ix_questions_course_module'), 'questions', ['course_id', 'module_id'], unique=False)
    op.create_index(op.f('ix_questions_course_material'), 'questions', ['course_id', 'material_id'], unique=False)
    op.alter_column('questions', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('questions', 'grading_rubric',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('questions', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
