"""adding snapshot_image_key to exam questions

Revision ID: dfbfb121f6ef
Revises: 5ee235419b3a
Create Date: 2026-07-14 17:02:57.886041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbfb121f6ef'
down_revision: Union[str, Sequence[str], None] = '5ee235419b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_questions', sa.Column('snapshot_image_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_questions', 'snapshot_image_key')
    # ### end Alembic commands ###
