"""add default subscription_plan_id to organizations

Revision ID: e032cb71d7da
Revises: 89ea52bc21e7
Create Date: 2026-02-05 00:18:26.307800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e032cb71d7da'
down_revision: Union[str, Sequence[str], None] = '89ea52bc21e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
