"""add course_id to ai_request_logs table

Revision ID: e7c95895fde1
Revises: 12914d169817
Create Date: 2026-04-08 01:39:04.946571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c95895fde1'
down_revision: Union[str, Sequence[str], None] = '12914d169817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_request_logs', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_request_logs_course_id'), 'ai_request_logs', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_request_logs_course_id'), table_name='ai_request_logs')
    op.drop_column('ai_request_logs', 'course_id')
    # ### end Alembic commands ###
