"""your massge here

Revision ID: ebdf83029ce6
Revises: 69296e247a52
Create Date: 2026-02-13 16:54:30.392769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdf83029ce6'
down_revision: Union[str, Sequence[str], None] = '69296e247a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_invitations_created_by_fkey'), 'course_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'course_invitations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('courses_created_by_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_created_by_fkey'), 'courses', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'course_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('course_invitations_created_by_fkey'), 'course_invitations', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
