"""ubdating ai caht tabels vr4

Revision ID: fcb00f5e9f1a
Revises: 0d71c5b372fc
Create Date: 2026-06-13 18:57:49.195654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb00f5e9f1a'
down_revision: Union[str, Sequence[str], None] = '0d71c5b372fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_messages', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_chat_messages', 'status')
    # ### end Alembic commands ###
